export const DELAY_AFTER_SUCCESSFULLY_ACTION = 1500;
export const DEFAULT_MAX_TEXT_LENGTH_RATIO = 50;
export const MAX_BOOK_TITLE_LENGTH_RATIO = 50;
export const MAX_BOOK_AUTHOR_LENGTH_RATIO = 48;

export const GRAPHIC_BOOK_TYPE = 0;
export const DIGITAL_BOOK_TYPE = 1;
export const PRINTED_BOOK_TYPE = 2;
